version: '2'
services:
    fortend-app:
        image: fortend
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fortend-mysql:3306/fortend?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fortend-mysql:
        extends:
            file: mysql.yml
            service: fortend-mysql
